### PR TITLE
Started the basic corporate policies document for team reference

### PR DESCRIPTION
**Pull request by JMarlin**

### CODE REVIEW

**Comment by JMarlin** [comment]
@LaurenEBaker, @ChaaZee, @Jax47, @MoAlsa7, can you all please review and approve my initial proposed policies?

When everyone approves, I will merge and close.

**Review by Jax47 — APPROVED** [review]

**Comment by LaurenEBaker** [comment]
looks good to me

**Review by LaurenEBaker — APPROVED** [review]
looks good

**Review by MoAlsa7 — APPROVED** [review]

**Review by ChaaZee — APPROVED** [review]

**Comment by JMarlin** [comment]
Thanks, all! Merging and closing.

**Pull request merged**
